name: flutter_sample_auto_route
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  auto_route: ^6.3.0
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.5
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  roggle: ^0.3.1
  universal_platform: ^1.0.0+1
  url_strategy: 0.2.0

dev_dependencies:
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3
  custom_lint: ^0.3.4
  pedantic_mono: ^1.21.1
  riverpod_lint: ^1.3.1

flutter:
  uses-material-design: true
